# Change to true for Disqus comments
# This would be the main block for adding subpages


disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:  

  - name: 'Current Research'
    path: 'menu'       # Blank means root | root = cv.html
    submenu:
    - name: 'Current Research'
      url:  'currentresearch.html'
    - name: 'Publications'
      url:  'publications.html'
   

   
  - name: 'California GrassNet'
    path: 'menu'
    submenu: 
    - name: 'About GrassNet'    
      url:  'aboutgrassnet.html'
    - name: 'Grassland Restoration Practitioners'
      url:  'Grasslandrestorationpractitioners.html'
    - name: 'Restoration Projects'
      url:  'Restorationprojects.html'
    - name: 'Resources for Grassland Restoration'
      url:  'Resourcesforgrasslandrestoration.html'
    - name: 'Library for Germination Protocols'
      url:  'seed-germination-library.html'
    - name: 'California Conservation Policy Library' 
      url:  'policy-library.html'
  

    
  - name: 'People'
    path: 'menu'
    submenu:
      - name: 'Justin Luong'
        url:  'justinluong.html'
      - name: 'Current Lab Associates'
        url:  'currentpeople.html'
      - name: 'Lab Alum'
        url:  'labalum.html'

        
 
    
  - name: 'Art & Science'
    path: 'menu'
    submenu:
      - name: 'Illustrated Summaries'
        url: 'illustratedsummaries.html'
      - name: 'Infographics'
        url: 'infographics.html'
      - name: 'Photos'
        url:  'photos.html'
    #removing parent URL links dropdown


    
  - name: 'Contact'
    path: 'menu'
    url: 'contact.html'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/justinluong/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UC-3p5ABk3vPzAE80evNdfYg'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Justin-Luong', type: 'png'}
- {icon: 'envelope', link: 'mailto:justinluong@berkeley.edu'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
 
