# Change to true for Disqus comments
# This would be the main block for adding subpages

#Sub page menu breakout
# Grassnet 
# about grassnet (home page)
# Reousrces (last)
# get involved
#
# people
# Current mmebres 
#past membners 
#
#research
# current publications
# past publications
#
#
#

disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
  - name: CV
    path: 'menu'      # Blank means root | root = cv.html
    url: 'cv.html'
    
  - name: 'Publications'
    path: 'menu'   # = /menu/publications.html
    url: 'publications.html'
    
  - name: 'Current Research'
    path: 'menu'
  #  submenu:
  #    - name: 'Current Research'
  #     url:
  #    - name: 'Past Research'
  #      url:
    url: 'currentresearch.html'
    
  - name: 'Presentations'
    path: 'menu'
    url: 'presentations.html'

  - name: 'People'
    path: 'menu'
    url: 'people.html'
    
  - name: 'Art & Science'
    path: 'menu'
    submenu:
      - name: 'Illustrated Summaries'
        url: 'illustratedsummaries.html'
      - name: 'Infographics'
        url: 'infographics.html'
    #removing parent URL links dropdown

  - name: 'California GRASS-Net'
    path: 'menu'
    submenu: 
    - name: 'About GrassNet'     #Home and first subpage
      url:  'aboutgrassnet.html
  #   - name: 'get Involved'       #Middle subpage
  #     url:
  #   - name: 'Resources'          #Last subpage
  #     url:
    url: 'grassnet.html'
    
  - name: 'Contact'
    path: 'menu'
    url: 'contact.html'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/JustinCLuong'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/justinluong/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UC-3p5ABk3vPzAE80evNdfYg'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Justin-Luong'}
- {icon: 'envelope', link: 'mailto:jluong4@ucsc.edu'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
 
